# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f31d092321ae813ba3d32a085cb0cb3ec8efd357a1a216fa986cb97b9f240a912a07c5aadd0ba7ccf29f8726dfc0be796966eba0bc213cbbb233e255639b14d1

test:
  secret_key_base: 436d74678696f0b0abb153fa73f285153bfc1892abdae4befc84a6a9fa492ddfabbd487e1cb926a912467e39c1a2d3da27dde7e3d49d542c33e42a5f05deda0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
